### ISSUE TITLE
Wrong repository link on marketplace

### ISSUE THREAD

**Issue by Nachh** [owozsh/sweeney#1]
Hi, when I went to thank you for creating this theme I noticed that in the marketplace is linking to your yogokai theme (that is awesome too).

By the way, thank you for such a nice color theme, I've long been tired of the Nord variants but couldn't find something that suited my eye just as well. This was love at first sight.

**Comment by owozsh** [comment]
Woow, thank you so much, I'm really glad that you're enjoying it :D

By the time I'm writing, an update with light mode is being deployed.

I've also added git colors, fixed some css colors and made comments more subtle.
